twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_env: '%app_env%'
        local: '%locale%'

when@test:
    twig:
        strict_variables: true
